### ISSUE TITLE
[Bug] 偶尔发生异常导致后台线程结束

### ISSUE THREAD

**Issue by jie65535** [virtcat/auto-shawarma#9]
以下是日志：

```log
24:20 >> Append order 4: swm(1,0,0,0),cola:(0,0),fries:2,juice:1,kibbeh:1
24:22 >> Make Shawarm: swm(1,0,0,0)
24:24 >> Append order 2: swm(0,1,1,0),cola:(0,0),fries:2,juice:0,kibbeh:1
24:25 >> Make Shawarm: swm(0,1,1,0)
Exception in thread Thread-1 (main_loop):
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "G:\Games\Shawarma\auto-shawarma\main.py", line 542, in main_loop
    if s == data.Shawarma() or not any(s == x[1] for x in old):
  File "G:\Games\Shawarma\auto-shawarma\main.py", line 542, in <genexpr>
    if s == data.Shawarma() or not any(s == x[1] for x in old):
TypeError: 'NoneType' object is not subscriptable
```

另外，在发生异常后，整个应用除于假死状态，无法退出，Ctrl+C也没有效果，只能关闭终端才能强制退出。

**Comment by virtcat** [comment]
修了 e1c2afe05eb018f54f2fc2296700ceca380113b4
